Repository openshift/operator-framework-catalogd, pull requests merged in 2024-07, with the labels that each got.

#54 NO-ISSUE: add everettraven to approvers+reviewers
  DOWNSTREAM_OWNERS_ALIASES
Labels: lgtm, jira/valid-reference, approved

#56 OPRUN-3428: UPSTREAM: <carry>: add openshift kustomize overlay
  openshift/generate-manifests.sh
  openshift/kustomize/overlays/openshift/kustomization.yaml
  openshift/kustomize/overlays/openshift/patches/catalogserver_service_port.yaml
  openshift/kustomize/overlays/openshift/patches/manager_deployment_certs.yaml
  openshift/kustomize/overlays/openshift/patches/manager_service.yaml
  openshift/manifests/12-service-openshift-catalogd-catalogd-catalogserver.yml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: lgtm, needs-ok-to-test, jira/valid-reference, approved

#57 NO-ISSUE: Synchronize From Upstream Repositories
  .bingo/ginkgo.mod
  .bingo/ginkgo.sum
  commitchecker.yaml
  config/base/manager/manager.yaml
  go.mod
  go.sum
  openshift/generate-manifests.sh
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  test/tools/imageregistry/registry.sh
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/pusher.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/referrers.go
  vendor/github.com/google/go-containerregistry/pkg/v1/remote/write.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, tide/merge-method-merge, approved, acknowledge-critical-fixes-only

#58 [release-4.15] OCPBUGS-36885: Set required-scc for openshift workloads
  openshift/generate-manifests.sh
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: backport-risk-assessed, qe-approved, lgtm, jira/valid-reference, jira/valid-bug, approved, cherry-pick-approved
