Repository openshift/operator-framework-catalogd, pull requests merged in 2024-11, with the labels that each got.

#88 NO-ISSUE: Synchronize From Upstream Repositories
  README.md
  api/core/doc.go
  api/v1/clustercatalog_types.go
  api/v1/clustercatalog_types_test.go
  api/v1/groupversion_info.go
  api/v1/zz_generated.deepcopy.go
  cmd/manager/main.go
  commitchecker.yaml
  config/base/crd/bases/olm.operatorframework.io_clustercatalogs.yaml
  config/base/default/clustercatalogs/default-catalogs.yaml
  config/base/manager/webhook/manifests.yaml
  config/samples/core_v1_clustercatalog.yaml
  docs/fetching-catalog-contents.md
  internal/controllers/core/clustercatalog_controller.go
  internal/controllers/core/clustercatalog_controller_test.go
  internal/garbagecollection/garbage_collector.go
  internal/garbagecollection/garbage_collector_test.go
  internal/source/containers_image.go
  internal/source/containers_image_test.go
  internal/source/unpacker.go
  internal/webhook/cluster_catalog_webhook.go
  internal/webhook/cluster_catalog_webhook_test.go
  openshift/kustomize/overlays/openshift/catalogs/openshift-certified-operators.yaml
  openshift/kustomize/overlays/openshift/catalogs/openshift-community-operators.yaml
  openshift/kustomize/overlays/openshift/catalogs/openshift-redhat-marketplace.yaml
  openshift/kustomize/overlays/openshift/catalogs/openshift-redhat-operators.yaml
  openshift/manifests/01-customresourcedefinition-clustercatalogs.olm.operatorframework.io.yml
  openshift/manifests/14-clustercatalog-openshift-certified-operators.yml
  openshift/manifests/15-clustercatalog-openshift-community-operators.yml
  openshift/manifests/16-clustercatalog-openshift-redhat-marketplace.yml
  openshift/manifests/17-clustercatalog-openshift-redhat-operators.yml
  openshift/manifests/18-mutatingwebhookconfiguration-catalogd-mutating-webhook-configuration.yml
  pprof/README.md
  test/e2e/e2e_suite_test.go
  test/e2e/unpack_test.go
  test/e2e/util.go
  test/tools/imageregistry/pre-upgrade-setup.sh
  test/upgrade/unpack_test.go
  test/upgrade/upgrade_suite_test.go
Labels: lgtm, jira/valid-reference, tide/merge-method-merge, approved

#92 OPRUN-3605: UPSTREAM: <carry>: namespace: use privileged PSA for audit and warn levels
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_namespace_privileged.yaml
  openshift/manifests/00-namespace-openshift-catalogd.yml
Labels: lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#93 NO-ISSUE: Adding Lalatendu Mohanty as an approver
  DOWNSTREAM_OWNERS_ALIASES
Labels: lgtm, jira/valid-reference, approved
