Repository openshift/operator-framework-catalogd, pull requests merged in 2025-01, with the labels that each got.

#101 OCPBUGS-46480: CVE-2024-12698 ose-olm-catalogd-container: incomplete fix for rapid reset (CVE-2023-39325/CVE-2023-44487) [openshift-4.18]
  cmd/manager/main.go
Labels: backport-risk-assessed, qe-approved, lgtm, jira/valid-reference, jira/valid-bug, approved, jira/severity-moderate, cherry-pick-approved

#105 OPRUN-3681: Add support for proxy trustedCAs
  openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/trusted-ca/catalogd_trusted_ca_configmap.yaml
  openshift/manifests/12-configmap-openshift-catalogd-catalogd-trusted-ca-bundle.yml
  openshift/manifests/13-service-openshift-catalogd-catalogd-service.yml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/manifests/15-clustercatalog-openshift-certified-operators.yml
  openshift/manifests/16-clustercatalog-openshift-community-operators.yml
  openshift/manifests/17-clustercatalog-openshift-redhat-marketplace.yml
  openshift/manifests/18-clustercatalog-openshift-redhat-operators.yml
  openshift/manifests/19-mutatingwebhookconfiguration-catalogd-mutating-webhook-configuration.yml
Labels: qe-approved, lgtm, jira/valid-reference, approved, acknowledge-critical-fixes-only

#113 OCPBUGS-48639: Add support for proxy trustedCAs
  openshift/kustomize/overlays/openshift/olmv1-ns/kustomization.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/kustomize/overlays/openshift/olmv1-ns/trusted-ca/catalogd_trusted_ca_configmap.yaml
  openshift/manifests/12-configmap-openshift-catalogd-catalogd-trusted-ca-bundle.yml
  openshift/manifests/13-service-openshift-catalogd-catalogd-service.yml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
  openshift/manifests/15-clustercatalog-openshift-certified-operators.yml
  openshift/manifests/16-clustercatalog-openshift-community-operators.yml
  openshift/manifests/17-clustercatalog-openshift-redhat-marketplace.yml
  openshift/manifests/18-clustercatalog-openshift-redhat-operators.yml
  openshift/manifests/19-mutatingwebhookconfiguration-catalogd-mutating-webhook-configuration.yml
Labels: backport-risk-assessed, qe-approved, lgtm, jira/valid-reference, jira/valid-bug, approved, cherry-pick-approved

#114 OCPBUGS-48640: Add service-ca into catalogd trusted certs
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: lgtm, jira/valid-reference, jira/valid-bug, approved, acknowledge-critical-fixes-only

#115 OCPBUGS-48639: Add service-ca into catalogd trusted certs [release-4.18]
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: backport-risk-assessed, lgtm, jira/valid-reference, jira/valid-bug, approved, cherry-pick-approved

#116 OCPBUGS-46516: improve logging: catalog http server
  go.mod
  go.sum
  internal/serverutil/serverutil.go
  vendor/github.com/gorilla/handlers/.editorconfig
  vendor/github.com/gorilla/handlers/.gitignore
  vendor/github.com/gorilla/handlers/LICENSE
  vendor/github.com/gorilla/handlers/Makefile
  vendor/github.com/gorilla/handlers/README.md
  vendor/github.com/gorilla/handlers/canonical.go
  vendor/github.com/gorilla/handlers/compress.go
  vendor/github.com/gorilla/handlers/cors.go
  vendor/github.com/gorilla/handlers/doc.go
  vendor/github.com/gorilla/handlers/handlers.go
  vendor/github.com/gorilla/handlers/logging.go
  vendor/github.com/gorilla/handlers/proxy_headers.go
  vendor/github.com/gorilla/handlers/recovery.go
  vendor/modules.txt
Labels: lgtm, jira/valid-reference, jira/valid-bug, approved, acknowledge-critical-fixes-only

#120 OCPBUGS-48830: UPSTREAM: <carry>: resolve issue with pre-mature mounting of trusted CA configmap
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: jira/severity-important, lgtm, jira/valid-reference, jira/valid-bug, approved, acknowledge-critical-fixes-only

#121 OCPBUGS-48795: Add /etc/docker to the catalogd deployment
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_mount_etc_containers.yaml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: jira/severity-important, lgtm, jira/valid-reference, jira/valid-bug, approved, acknowledge-critical-fixes-only

#125 OCPBUGS-49439: Resolve issue with pre-mature mounting of service CA configmap
  openshift/kustomize/overlays/openshift/olmv1-ns/patches/manager_deployment_certs.yaml
  openshift/manifests/14-deployment-openshift-catalogd-catalogd-controller-manager.yml
Labels: jira/severity-important, backport-risk-assessed, lgtm, jira/valid-reference, jira/valid-bug, approved, cherry-pick-approved, acknowledge-critical-fixes-only

#127 OCPBUGS-49622: Fix leaderelection settings
  cmd/manager/main.go
Labels: backport-risk-assessed, lgtm, jira/valid-reference, jira/valid-bug, approved, cherry-pick-approved
